/**
 * sitemap.xml, robots.txt, llms.txt, and the non-production `_headers` file.
 *
 * Pure builders. `scripts/write-agent-artifacts.ts` reads `content/bf/**` and
 * calls these during `nuxt generate`. Nothing here is written into `public/`
 * for git to commit.
 */
import { SITE_NAME, canonicalUrl, oneLine } from './site'

export interface SitemapUrl {
  loc: string
  lastmod?: string
}

export interface LlmsLink {
  href: string
  title: string
  description?: string
}

export interface LlmsSection {
  heading: string
  links: LlmsLink[]
}

export const ROBOTS_DISALLOW = ['/docs/', '/wireframes/', '/search'] as const

/** Named AI crawlers. Each group repeats the public-site disallows — a specific group does not inherit `*`. */
export const AI_CRAWLERS = [
  'GPTBot',
  'ChatGPT-User',
  'OAI-SearchBot',
  'Google-Extended',
  'anthropic-ai',
  'ClaudeBot',
  'PerplexityBot',
  'Applebot-Extended',
  'cohere-ai',
  'CCBot'
] as const

function xmlEscape(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

export function sitemapXml(urls: SitemapUrl[]): string {
  const body = [...urls]
    .sort((a, b) => (a.loc < b.loc ? -1 : a.loc > b.loc ? 1 : 0))
    .map(url => {
      const lastmod = url.lastmod
        ? `\n    <lastmod>${xmlEscape(url.lastmod)}</lastmod>`
        : ''
      return `  <url>\n    <loc>${xmlEscape(url.loc)}</loc>${lastmod}\n  </url>`
    })
    .join('\n')
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${body}\n</urlset>\n`
}

function robotGroup(agent: string): string {
  const lines = [`User-agent: ${agent}`, 'Allow: /']
  for (const path of ROBOTS_DISALLOW) lines.push(`Disallow: ${path}`)
  return lines.join('\n')
}

export function robotsTxt(siteUrl: string): string {
  const groups = ['*', ...AI_CRAWLERS].map(agent => robotGroup(agent))
  return `${groups.join('\n\n')}\n\nSitemap: ${canonicalUrl(siteUrl, '/sitemap.xml')}\n`
}

/**
 * `_headers` for a Netlify deploy context.
 *
 * Netlify does not apply per-context `[[headers]]` in netlify.toml. The build
 * writes this file only when `CONTEXT` is set and is not `production`
 * (branch deploys such as `dev-preview`, deploy previews). An unset context
 * — a local generate — writes nothing, so a production artifact is not noindexed.
 */
export function noindexHeaders(context: string | undefined): string | null {
  if (!context || context === 'production') return null
  return [
    '# Generated by scripts/write-agent-artifacts.ts.',
    '# Netlify has no per-context [[headers]] table; this file is written only when CONTEXT is not production.',
    '/*',
    '  X-Robots-Tag: noindex',
    ''
  ].join('\n')
}

export function whenToUse(programs: { name: string, path: string }[]): string {
  const named = programs.map(program => `${program.name} (${program.path})`).join('; ')
  return [
    'Use this site when the question is about the Bertelsmann Foundation North America itself: who runs it, what it publishes, and which program or project a piece of work belongs to.',
    '',
    'Read these pages for these jobs:',
    '',
    '- Who the foundation is, who sits on the board and staff, and how it relates to the Bertelsmann Stiftung: /about',
    '- How to write to the foundation (info@bfna.org) or use the message form: /contact and /about#contact',
    '- What this website collects and what it does not: /privacy',
    '- A research piece, byline, or publication date: /insights and the insight\'s own URL',
    `- What a program covers${named ? ` (${named})` : ''}: that program's URL`,
    '- A project, fellowship, documentary series, or tool such as RANGE: /projects and the project\'s own URL',
    '- Older work that stays online: /archive',
    '',
    'This site is not a software product. It does not offer a public API, an API key, or a sandbox. An internal design-system preview ships on the same host and is omitted from this file on purpose; it is not a developer portal. For a machine-readable index of the public pages, use /sitemap.xml and this file.'
  ].join('\n')
}

export function llmsTxt(input: {
  summary: string
  whenToUse: string
  sections: LlmsSection[]
}): string {
  const sections = input.sections
    .filter(section => section.links.length > 0)
    .map(section => {
      const links = section.links.map(link => {
        const description = oneLine(link.description)
        const suffix = description ? `: ${description}` : ''
        return `- [${link.title}](${link.href})${suffix}`
      })
      return `## ${section.heading}\n\n${links.join('\n')}`
    })
  return [
    `# ${SITE_NAME}`,
    '',
    `> ${oneLine(input.summary, 600)}`,
    '',
    '## When to use this site',
    '',
    input.whenToUse.trim(),
    '',
    sections.join('\n\n')
  ].join('\n').replace(/\n{3,}/g, '\n\n').trim() + '\n'
}
