import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { afterEach, describe, expect, it } from 'vitest'
import { generateAgentArtifacts, readableMarkdown, renderLlms, renderRobots, renderSitemap, validPublishDate } from '../../../scripts/generate-agent-artifacts'
import { isDiscoverableRoute, markdownOutputPath } from '../../../scripts/lib/agent-routes'

const temporaryRoots: string[] = []
afterEach(async () => Promise.all(temporaryRoots.splice(0).map(path => rm(path, { recursive: true, force: true }))))
const page = (slug: string, heading: string, publishDate: string | null = null) => ({ slug, heading, subheading: `${heading} summary`, excerpt: `${heading} excerpt`, description: `## ${heading} section\n\nFirst paragraph.\n\nSecond paragraph.`, authors: [], image: null, video_url: null, download: null, external_url: null, publish_date: publishDate, bucket: 'page', format: null, kind: null, program: null, archived: false, evergreen: true, copy_source: 'test', legacy: null })

describe('agent artifact renderers', () => {
  it('validates calendar dates strictly and never accepts timestamps', () => { expect(validPublishDate('2025-02-24')).toBe('2025-02-24'); expect(validPublishDate('2025-02-30')).toBeUndefined(); expect(validPublishDate('2025-02-24T00:00:00Z')).toBeUndefined(); expect(validPublishDate(null)).toBeUndefined() })
  it('preserves readable headings and paragraph breaks', () => expect(readableMarkdown('<h2>Heading</h2><p>One.</p><p>Two.</p>')).toBe('Heading\n\nOne.\n\nTwo.'))
  it('renders valid lastmod only and excludes utility routes', () => { const documents = [{ route: '/', title: 'Home', description: 'Home', body: 'Body', publishDate: '2025-02-24' }, { route: '/about', title: 'About', description: 'About', body: 'Body' }]; const sitemap = renderSitemap(documents); expect(sitemap).toContain('<lastmod>2025-02-24</lastmod>'); expect(sitemap.match(/<lastmod>/g)).toHaveLength(1); expect(renderLlms(documents)).toContain('## When to use this site'); expect(renderRobots()).toContain('Disallow: /docs/'); expect(renderRobots()).toContain('Disallow: /wireframes/'); expect(renderRobots()).toContain('Disallow: /search'); expect(isDiscoverableRoute('/docs/button')).toBe(false); expect(isDiscoverableRoute('/insights/example')).toBe(true); expect(markdownOutputPath('/')).toBe('index.md') })
  it('writes twins/discovery/404 and scopes _headers to non-production', async () => { const root = await mkdtemp(join(tmpdir(), 'bfna-agent-')); temporaryRoots.push(root); const content = join(root, 'content/bf/pages'); const output = join(root, '.output/public'); await mkdir(content, { recursive: true }); await Promise.all([writeFile(join(content, 'home.json'), JSON.stringify(page('home', 'Home', '2025-02-24'))), writeFile(join(content, 'about.json'), JSON.stringify(page('about', 'About'))), writeFile(join(content, 'archive.json'), JSON.stringify(page('archive', 'Archive'))), writeFile(join(content, 'privacy.json'), JSON.stringify(page('privacy', 'Privacy')))]); await generateAgentArtifacts(root, output, 'deploy-preview'); expect(await readFile(join(output, 'index.md'), 'utf8')).toContain('\n\nFirst paragraph.\n\nSecond paragraph.'); expect(await readFile(join(output, 'sitemap.xml'), 'utf8')).not.toContain('/search'); expect(await readFile(join(output, 'llms.txt'), 'utf8')).toContain('## When to use this site'); expect(await readFile(join(output, '404.html'), 'utf8')).toContain('Page not found'); expect(await readFile(join(output, '_headers'), 'utf8')).toContain('X-Robots-Tag: noindex, nofollow'); await generateAgentArtifacts(root, output, 'production'); await expect(readFile(join(output, '_headers'), 'utf8')).rejects.toMatchObject({ code: 'ENOENT' }) })
})
