/**
 * Site chrome — the top-bar / footer menu structure, as data.
 *
 * `menus.json` is GENERATED by `scripts/normalise-wireframe-data.ts` (issue 08) from
 * the `MENUS` constant that `useWfContent.ts` hardcodes today; do not hand-edit it.
 * This module is the hand-authored typed accessor over it. The annotation below is a
 * real assignability check — a missing or wrongly-typed known property fails
 * `nuxt typecheck` rather than reaching a component. It is not an exactness check:
 * `menusJson` is an imported binding, not a fresh object literal, so TypeScript's
 * excess-property check does not apply and an extra or misspelled key would pass
 * silently. `scripts/` sits outside the app tsconfig's `include`, so this module is
 * the only compile-time gate on the generated file's shape.
 *
 * `Menu` / `MenuItem` come from `~/types/bf-contracts` (issue 02) and are reused
 * directly — BRIEF §5 rule 11 forbids redeclaring a shared shape here.
 *
 * BRIEF §6: menus are a typed JSON module, NOT a seventh `@nuxt/content` collection.
 * The layout reads this and passes it as a prop to `bfNav` / `bfFooter`, which stay
 * presentational (D8).
 */
import type { Menu } from '~/types/bf-contracts'
import menusJson from './menus.json'

export const menus: Menu[] = menusJson

export default menus
